export type CountryName =
  | "Afghanistan"
  | "Aland Islands"
  | "Aland"
  | "Åland"
  | "Åland Islands"
  | "Albania"
  | "Algeria"
  | "American Samoa"
  | "Andorra"
  | "Angola"
  | "Anguilla"
  | "Antarctica"
  | "Antigua and Barbuda"
  | "Argentina"
  | "Armenia"
  | "Aruba"
  | "Australia"
  | "Austria"
  | "Azerbaijan"
  | "Bahamas"
  | "The Bahamas"
  | "Bahrain"
  | "Bangladesh"
  | "Barbados"
  | "Belarus"
  | "Belgium"
  | "Belize"
  | "Benin"
  | "Bermuda"
  | "Bhutan"
  | "Bolivia"
  | "Plurinational State of Bolivia"
  | "Bosnia and Herzegovina"
  | "Botswana"
  | "Bouvet Island"
  | "Brazil"
  | "British Indian Ocean Territory"
  | "British Virgin Islands"
  | "Virgin Islands"
  | "Virgin Islands (British)"
  | "Brunei"
  | "Brunei Darussalam"
  | "Bulgaria"
  | "Burkina Faso"
  | "Burundi"
  | "Cambodia"
  | "Cameroon"
  | "Canada"
  | "Cape Verde"
  | "Cabo Verde"
  | "Caribbean Netherlands"
  | "Bonaire, Sint Eustatius and Saba"
  | "Cayman Islands"
  | "Central African Republic"
  | "Chad"
  | "Chile"
  | "China"
  | "People's Republic of China"
  | "PRC"
  | "Christmas Island"
  | "Cocos (Keeling) Islands"
  | "Colombia"
  | "Comoros"
  | "Cook Islands"
  | "Costa Rica"
  | "Croatia"
  | "Cuba"
  | "Curacao"
  | "Curaçao"
  | "Cyprus"
  | "Czechia"
  | "Czech Republic"
  | "Democratic Republic of the Congo"
  | "Congo-Kinshasa"
  | "DR Congo"
  | "DRC"
  | "Denmark"
  | "Djibouti"
  | "Dominica"
  | "Dominican Republic"
  | "Ecuador"
  | "Egypt"
  | "El Salvador"
  | "Equatorial Guinea"
  | "Eritrea"
  | "Estonia"
  | "Eswatini"
  | "Swaziland"
  | "Ethiopia"
  | "Falkland Islands"
  | "Falkland Islands (Malvinas)"
  | "Falklands"
  | "Faroe Islands"
  | "Fiji"
  | "Finland"
  | "France"
  | "French Guiana"
  | "French Polynesia"
  | "French Southern Territories"
  | "French Southern and Antarctic Lands"
  | "French Southern Lands"
  | "Gabon"
  | "Gambia"
  | "The Gambia"
  | "Georgia"
  | "Germany"
  | "Ghana"
  | "Gibraltar"
  | "Greece"
  | "Greenland"
  | "Grenada"
  | "Guadeloupe"
  | "Guam"
  | "Guatemala"
  | "Guernsey"
  | "Guinea"
  | "Guinea-Bissau"
  | "Guyana"
  | "Haiti"
  | "Heard Island and McDonald Islands"
  | "Honduras"
  | "Hong Kong"
  | "HK"
  | "Hong Kong SAR"
  | "Hungary"
  | "Iceland"
  | "India"
  | "Indonesia"
  | "Iran"
  | "Islamic Republic of Iran"
  | "Iraq"
  | "Ireland"
  | "Isle of Man"
  | "Israel"
  | "Italy"
  | "Ivory Coast"
  | "Cote d'Ivoire"
  | "Côte d'Ivoire"
  | "Jamaica"
  | "Japan"
  | "Jersey"
  | "Jordan"
  | "Kazakhstan"
  | "Kenya"
  | "Kiribati"
  | "Kosovo"
  | "Kuwait"
  | "Kyrgyzstan"
  | "Laos"
  | "Lao People's Democratic Republic"
  | "Latvia"
  | "Lebanon"
  | "Lesotho"
  | "Liberia"
  | "Libya"
  | "Liechtenstein"
  | "Lithuania"
  | "Luxembourg"
  | "Macau"
  | "Macao"
  | "Macao SAR"
  | "Madagascar"
  | "Malawi"
  | "Malaysia"
  | "Maldives"
  | "Mali"
  | "Malta"
  | "Marshall Islands"
  | "Martinique"
  | "Mauritania"
  | "Mauritius"
  | "Mayotte"
  | "Mexico"
  | "Micronesia"
  | "Federated States of Micronesia"
  | "Moldova"
  | "Republic of Moldova"
  | "Monaco"
  | "Mongolia"
  | "Montenegro"
  | "Montserrat"
  | "Morocco"
  | "Mozambique"
  | "Myanmar"
  | "Namibia"
  | "Nauru"
  | "Nepal"
  | "Netherlands"
  | "Kingdom of the Netherlands"
  | "New Caledonia"
  | "New Zealand"
  | "Nicaragua"
  | "Niger"
  | "Nigeria"
  | "Niue"
  | "Norfolk Island"
  | "North Korea"
  | "Democratic People's Republic of Korea"
  | "DPRK"
  | "North Macedonia"
  | "Macedonia"  
  | "Northern Mariana Islands"
  | "Norway"
  | "Oman"
  | "Pakistan"
  | "Palau"
  | "Palestine"
  | "State of Palestine"
  | "Panama"
  | "Papua New Guinea"
  | "Paraguay"
  | "Peru"
  | "Philippines"
  | "Pitcairn Islands"
  | "Pitcairn"
  | "Pitcairn, Henderson, Ducie and Oeno Islands"
  | "Poland"
  | "Portugal"
  | "Puerto Rico"
  | "Qatar"
  | "Republic of the Congo"
  | "Congo Republic"
  | "Congo-Brazzaville"
  | "Reunion"
  | "Réunion"
  | "Romania"
  | "Russia"
  | "Russian Federation"
  | "Rwanda"
  | "Saint Barthelemy"
  | "Saint Barthélemy"
  | "Saint Helena"
  | "Saint Helena, Ascension and Tristan da Cunha"
  | "Saint Kitts and Nevis"
  | "Saint Lucia"
  | "Saint Martin"
  | "Saint Martin (French part)"
  | "Saint Pierre and Miquelon"
  | "Saint Vincent and the Grenadines"
  | "Samoa"
  | "San Marino"
  | "Sao Tome and Principe"
  | "Saudi Arabia"
  | "Senegal"
  | "Serbia"
  | "Seychelles"
  | "Sierra Leone"
  | "Singapore"
  | "Sint Maarten"
  | "Sint Maarten (Dutch part)"
  | "Slovakia"
  | "Slovenia"
  | "Solomon Islands"
  | "Somalia"
  | "South Africa"
  | "South Georgia and the South Sandwich Islands"
  | "South Korea"
  | "Republic of Korea"
  | "ROK"
  | "South Sudan"
  | "Spain"
  | "Sri Lanka"
  | "Sudan"
  | "Suriname"
  | "Svalbard and Jan Mayen"
  | "Svalbard and Jan Mayen Islands"
  | "Sweden"
  | "Switzerland"
  | "Syria"
  | "Syrian Arab Republic"
  | "Taiwan"
  | "Chinese Taipei"
  | "Republic of China"
  | "Tajikistan"
  | "Tanzania"
  | "United Republic of Tanzania"
  | "Thailand"
  | "Timor-Leste"
  | "Togo"
  | "Tokelau"
  | "Tonga"
  | "Trinidad and Tobago"
  | "Tunisia"
  | "Turkey"
  | "Türkiye"
  | "Turkmenistan"
  | "Turks and Caicos Islands"
  | "Tuvalu"
  | "Uganda"
  | "Ukraine"
  | "United Arab Emirates"
  | "UAE"
  | "United Kingdom"
  | "UK"
  | "United Kingdom of Great Britain and Northern Ireland"
  | "United States"
  | "U.S."
  | "United States of America"
  | "US"
  | "USA"
  | "United States Minor Outlying Islands"
  | "Uruguay"
  | "US Virgin Islands"
  | "U.S. Virgin Islands"
  | "United States Virgin Islands"
  | "Virgin Islands (U.S.)"
  | "Virgin Islands of the United States"
  | "Uzbekistan"
  | "Vanuatu"
  | "Vatican City"
  | "Holy See"
  | "Vatican"
  | "Vatican City State"
  | "Venezuela"
  | "Bolivarian Republic of Venezuela"
  | "Vietnam"
  | "Viet Nam"
  | "Wallis and Futuna"
  | "Wallis and Futuna Islands"
  | "Western Sahara"
  | "Sahrawi Republic"
  | "Yemen"
  | "Zambia"
  | "Zero Knowledge Republic"
  | "Zimbabwe"
;

export type CommonCountryName =
  | "Aland Islands"
  | "Bahamas"
  | "Bolivia"
  | "British Virgin Islands"
  | "Brunei"
  | "Cape Verde"
  | "Caribbean Netherlands"
  | "China"
  | "Curacao"
  | "Czechia"
  | "Democratic Republic of the Congo"
  | "Eswatini"
  | "Falkland Islands"
  | "French Southern Territories"
  | "Gambia"
  | "Hong Kong"
  | "Iran"
  | "Ivory Coast"
  | "Laos"
  | "Macau"
  | "Micronesia"
  | "Moldova"
  | "Netherlands"
  | "North Korea"
  | "North Macedonia"
  | "Palestine"
  | "Pitcairn Islands"
  | "Republic of the Congo"
  | "Reunion"
  | "Russia"
  | "Saint Barthelemy"
  | "Saint Helena"
  | "Saint Martin"
  | "Sint Maarten"
  | "South Korea"
  | "Svalbard and Jan Mayen"
  | "Syria"
  | "Taiwan"
  | "Tanzania"
  | "Turkey"
  | "United Arab Emirates"
  | "United Kingdom"
  | "United States"
  | "US Virgin Islands"
  | "Vatican City"
  | "Venezuela"
  | "Vietnam"
  | "Wallis and Futuna"
  | "Western Sahara"
;

export interface CountryEntry {
  name: CountryName;
  synonyms?: string[];
}
