import type { CommonCountryName } from "../types/countries"

export const COUNTRY_SYNONYMS: Record<CommonCountryName, string[]> = {
	"Aland Islands": ["Aland", "Åland", "Åland Islands"],
	"Bahamas": ["The Bahamas"],
	"Bolivia": ["Plurinational State of Bolivia"],
	"British Virgin Islands": ["Virgin Islands", "Virgin Islands (British)"],
	"Brunei": ["Brunei Darussalam"],
	"Cape Verde": ["Cabo Verde"],
	"Caribbean Netherlands": ["Bonaire, Sint Eustatius and Saba"],
	"China": ["People's Republic of China", "PRC"],
	"Curacao": ["Curaçao"],
	"Czechia": ["Czech Republic"],
	"Democratic Republic of the Congo": ["Congo-Kinshasa", "DR Congo", "DRC"],
	"Eswatini": ["Swaziland"],
	"Falkland Islands": ["Falkland Islands (Malvinas)", "Falklands"],
	"French Southern Territories": ["French Southern and Antarctic Lands", "French Southern Lands"],
	"Gambia": ["The Gambia"],
	"Hong Kong": ["HK", "Hong Kong SAR"],
	"Iran": ["Islamic Republic of Iran"],
	"Ivory Coast": ["Cote d'Ivoire", "Côte d'Ivoire"],
	"Laos": ["Lao People's Democratic Republic"],
	"Macau": ["Macao", "Macao SAR"],
	"Micronesia": ["Federated States of Micronesia"],
	"Moldova": ["Republic of Moldova"],
	"Netherlands": ["Kingdom of the Netherlands"],
	"North Korea": ["Democratic People's Republic of Korea", "DPRK"],
    "North Macedonia": ["Macedonia"],
	"Palestine": ["State of Palestine"],
	"Pitcairn Islands": ["Pitcairn", "Pitcairn, Henderson, Ducie and Oeno Islands"],
	"Republic of the Congo": ["Congo Republic", "Congo-Brazzaville"],
	"Reunion": ["Réunion"],
	"Russia": ["Russian Federation"],
	"Saint Barthelemy": ["Saint Barthélemy"],
	"Saint Helena": ["Saint Helena, Ascension and Tristan da Cunha"],
	"Saint Martin": ["Saint Martin (French part)"],
	"Sint Maarten": ["Sint Maarten (Dutch part)"],
	"South Korea": ["Republic of Korea", "ROK"],
	"Svalbard and Jan Mayen": ["Svalbard and Jan Mayen Islands"],
	"Syria": ["Syrian Arab Republic"],
	"Taiwan": ["Chinese Taipei", "Republic of China"],
	"Tanzania": ["United Republic of Tanzania"],
	"Turkey": ["Türkiye"],
	"United Arab Emirates": ["UAE"],
	"United Kingdom": ["UK", "United Kingdom of Great Britain and Northern Ireland"],
	"United States": ["U.S.", "United States of America", "US", "USA"],
	"US Virgin Islands": ["U.S. Virgin Islands", "United States Virgin Islands", "Virgin Islands (U.S.)", "Virgin Islands of the United States"],
	"Vatican City": ["Holy See", "Vatican", "Vatican City State"],
	"Venezuela": ["Bolivarian Republic of Venezuela"],
	"Vietnam": ["Viet Nam"],
	"Wallis and Futuna": ["Wallis and Futuna Islands"],
	"Western Sahara": ["Sahrawi Republic"],
}
